services:
  postgres:
    image: postgres:17
    container_name: gaia-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gaia
    ports:
      - "5432:5432"
    volumes:
      - gaia-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d gaia -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
volumes:
  gaia-pgdata:
