services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: dephy-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dephy
    restart: always
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d dephy -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - dephy-data:/var/lib/postgresql/data

volumes:
  dephy-data:
